from sqlalchemy import Column, Integer, Text, Float, DateTime
from sqlalchemy.orm import declarative_base
Base = declarative_base()
class Feedback(Base):
    __tablename__ = "feedback"
    feedback_id = Column(Text, primary_key=True)
    user_id = Column(Text)
    product = Column(Text)
    feedback_text = Column(Text)
    rating = Column(Integer)
    timestamp = Column(DateTime(timezone=True))
    month = Column(Text)
    channel = Column(Text)
    sentiment = Column(Text)
    sentiment_score = Column(Float)
    text_sentiment_score = Column(Float)
    sentiment_source = Column(Text)
    theme = Column(Text)
    theme_match_score = Column(Float)
    theme_confidence = Column(Text)
    feedback_count = Column(Integer)
    negative_count = Column(Integer)
    negative_rate = Column(Float)
    month_over_month_change = Column(Float)
    month_over_month_change_pct = Column(Float)
    emerging_status = Column(Text)
    emerging_emerging_score = Column(Float)
    emerging_feedback_change = Column(Float)
    emerging_feedback_change_pct = Column(Float)
    emerging_negative_change = Column(Float)
    emerging_latest_negative_rate = Column(Float)
    issue_priority = Column(Text)
    agent_signal = Column(Text)
    memory_text = Column(Text)
