CREATE TABLE IF NOT EXISTS feedback (
    feedback_id TEXT,
    user_id TEXT,
    product TEXT,
    feedback_text TEXT,
    rating INTEGER,
    timestamp TIMESTAMPTZ,
    month TEXT,
    channel TEXT,
    sentiment TEXT,
    sentiment_score DOUBLE PRECISION,
    text_sentiment_score DOUBLE PRECISION,
    sentiment_source TEXT,
    theme TEXT,
    theme_match_score DOUBLE PRECISION,
    theme_confidence DOUBLE PRECISION,
    feedback_count INTEGER,
    negative_count INTEGER,
    negative_rate DOUBLE PRECISION,
    month_over_month_change DOUBLE PRECISION,
    month_over_month_change_pct DOUBLE PRECISION,
    emerging_status TEXT,
    emerging_emerging_score DOUBLE PRECISION,
    emerging_feedback_change DOUBLE PRECISION,
    emerging_feedback_change_pct DOUBLE PRECISION,
    emerging_negative_change DOUBLE PRECISION,
    emerging_latest_negative_rate DOUBLE PRECISION,
    issue_priority TEXT,
    agent_signal TEXT,
    memory_text TEXT
);